### ISSUE TITLE
Create new Tour and Tourversion

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-e2e#230]
**Test shall include:**

- Customer Fixtures to use: (if needed)
- What to test
- Expectation for the test to be successful

https://recordit.co/Xx7s0Nhsfu

Todo for developer (besides coding)
- Always make sure the issue is in the correct project lane
- [x] jenkins console URL / cypress dashboard URL to the successful test *suite* run (not just yours)
     * https://dashboard.cypress.io/#/projects/5yp4q1/runs/395/specs
- [x] get it integrated into `master`
  * [x] https://github.com/metasfresh/metasfresh-e2e/pull/235 (2019-07-25 - ts)
    - https://github.com/metasfresh/metasfresh-e2e/pull/235#pullrequestreview-266416562
All Flags are ticked? Congratulations, you have delivered!

**Comment by cristinastefan90** [comment]
Tour - the action of scheduling the product delivery. A customer may have multiple tour versions, one in the winter for example and one in the summer. A tour version is made based on a tour and has a validity:
![image](https://user-images.githubusercontent.com/50820854/61796722-aadf4b80-ae2e-11e9-8be1-b8a0ad442f58.png)

For example, if the * Weekly * checkbox is set and the preparation time is 1 PM that means that every Friday at 1 PM, the product is ready to be delivered to the customer.

In order to specify for which customer this schedule is made, the user has to add a new tour version line in which he will specify the customer, its location and buffer(the time between the delivery is ready to go and the actual time when it gets to him)
![image](https://user-images.githubusercontent.com/50820854/61797009-42dd3500-ae2f-11e9-8ae1-d7d1570b37ab.png)
